import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AppointmentsContextProvider from "@/src/contexts/AppointmentsContextProvider";
import ClientsContextProvider from "@/src/contexts/ClientsContextProvider";
import SearchContextProvider from "../contexts/SearchContextProvider";
import UsersContextProvider from "../contexts/UsersContexProvider";
import prisma from "../lib/db";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const appointments = await prisma.appointment.findMany()

  const clients = await prisma.client.findMany()

  const users = await prisma.user.findMany()

  return (
    <SearchContextProvider data={""}>
      <AppointmentsContextProvider data={appointments}>
        <ClientsContextProvider data={clients}>
          <UsersContextProvider data={users}>
          <html lang="en">
            <body className={inter.className}>
              {children}
            </body>
          </html>
          </UsersContextProvider>
        </ClientsContextProvider>
      </AppointmentsContextProvider>
    </SearchContextProvider>

  );
}
