import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AppointmentsContextProvider from "@/src/contexts/AppointmentsContextProvider";
import ClientsContextProvider, { ClientsContext } from "@/src/contexts/ClientsContextProvider";
import { TClient } from "../lib/types";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const appointments: [] = [];

  const clients: TClient[] = [
    {
      name: "Giacomo",
      surname: "Rossi",
      age: 40,
      key: "1",
    },
    {
      name: "Serena",
      surname: "Puliti",
      age: 32,
      key: "2",
    },
    {
      name: "Vasco",
      surname: "Brondi",
      age: 71,
      key: "3",
    }
  ];

  return (
    <AppointmentsContextProvider appointments={appointments}>
      <ClientsContextProvider clients={clients}>
        <html lang="en">
          <body className={inter.className}>{children}</body>
        </html>
      </ClientsContextProvider>
    </AppointmentsContextProvider>
  );
}
