import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AppointmentsContextProvider from "@/src/contexts/AppointmentsContextProvider";
import ClientsContextProvider from "@/src/contexts/ClientsContextProvider";
import SearchContextProvider from "../contexts/SearchContextProvider";
import UsersContextProvider from "../contexts/UsersContexProvider";
import prisma from "../lib/db";
import { Appointment } from "@prisma/client";
import { week } from "../lib/planner";
import CurrentDayContextProvider from "../contexts/CurrentDayContextProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

const clients = await prisma.client.findMany()

const users = await prisma.user.findMany()

const currentDay = new Date()

  return (
  <CurrentDayContextProvider data={currentDay}>
    <SearchContextProvider data={""}>
        <ClientsContextProvider data={clients}>
          <UsersContextProvider data={users}>
              <html lang="en">
                <body className={inter.className}>
                  {children}
                </body>
              </html>
          </UsersContextProvider>
        </ClientsContextProvider>
    </SearchContextProvider>
  </CurrentDayContextProvider>
  );
}
